# Generated by Django 2.1.7 on 2019-02-12 11:14

from django.core.files.base import ContentFile
from django.db import migrations


def copy_avatars(apps, schema_editor):
    User = apps.get_model('user', 'FruitUser')

    users = User.objects.exclude(avatar=None)
    count = users.count()

    for n, usr in enumerate(users, start=1):
        print('copying avatar {}/{}'.format(n, count))
        try:
            with open(usr.avatar.path, 'rb') as old_file:
                usr.avatar = ContentFile(old_file.read(), name=usr.avatar.name)
                usr.save()

        except FileNotFoundError:
            print('File {} does not exist!'.format(usr.avatar.path))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_fruituser_external_url'),
    ]

    operations = [
        migrations.RunPython(copy_avatars)
    ]
