# Generated by Django 2.1.7 on 2019-02-12 11:14
from django.core.files.base import ContentFile
from django.db import migrations


def copy_avatars(apps, schema_editor):
    FruitUser = apps.get_model('user', 'FruitUser')
    FruitUser.objects.filter(avatar='').update(avatar=None)
    users = FruitUser.objects.exclude(avatar=None)
    count = users.count()

    for n, user in enumerate(users, start=1):
        print('copying avatar {}/{}'.format(n, count))
        try:
            with open(user.avatar.path, 'rb') as old_file:
                user.avatar = ContentFile(old_file.read(), name=user.avatar.name)
                user.save()

        except (ValueError, FileNotFoundError) as e:
            print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_fruituser_external_url'),
    ]

    operations = [
        migrations.RunPython(copy_avatars)
    ]
