# Generated by Django 2.1.7 on 2019-02-22 12:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_move_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruituser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar', null=True, upload_to=user.models.FruitUser._upload_avatar_to, verbose_name='avatar'),
        ),
    ]
