# Generated by Django 2.0.8 on 2018-09-16 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruit', '0016_auto_20180916_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_cs', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('latin_name', models.CharField(blank=True, max_length=255, verbose_name='latin name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, help_text='Illustrational photo', null=True, upload_to='herbarium', verbose_name='photo')),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fruit.Kind', verbose_name='kind')),
            ],
            options={
                'verbose_name': 'herbarium item',
                'verbose_name_plural': 'herbarium items',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255, verbose_name='ripening plant part')),
                ('part_en', models.CharField(max_length=255, null=True, verbose_name='ripening plant part')),
                ('part_cs', models.CharField(max_length=255, null=True, verbose_name='ripening plant part')),
                ('start', utils.fields.MonthsField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, help_text='Month when specified plant part ripening starts.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='ripening start')),
                ('duration', utils.fields.MonthsField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, help_text='Duration of ripening in months.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='ripening duration')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='herbarium.Herbarium', verbose_name='herbarium item')),
            ],
            options={
                'verbose_name': 'ripening season',
                'verbose_name_plural': 'ripening seasons',
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('part', 'herb')},
        ),
    ]
