# Generated by Django 2.0.8 on 2018-09-16 12:46

from django.db import migrations


def copy_herbarium(apps, schema_editor):
    OldHerbarium = apps.get_model('fruit.herbarium', 'Herbarium')
    NewHerbarium = apps.get_model('herbarium', 'Herbarium')

    herbs = OldHerbarium.objects.all()
    count = herbs.count()

    for n, h in enumerate(herbs, start=1):
        print('copying herbarium item {}/{}'.format(n, count))

        NewHerbarium.objects.create(
            kind_id=h.kind_id,
            full_name=h.full_name,
            latin_name=h.latin_name,
            description=h.description,
            photo=h.photo,
        )


def copy_seasons(apps, schema_editor):
    OldSeason = apps.get_model('fruit.herbarium', 'Season')
    NewSeason = apps.get_model('herbarium', 'Season')

    seasons = OldSeason.objects.all()
    count = seasons.count()

    for n, s in enumerate(seasons, start=1):
        print('copying season {}/{}'.format(n, count))

        NewSeason.objects.create(
            herb_id=s.herb_id,
            part=s.part,
            start=s.start,
            duration=s.duration,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
        ('fruit', '0016_auto_20180916_1442'),
    ]

    operations = [
        migrations.RunPython(copy_herbarium),
        migrations.RunPython(copy_seasons),
    ]
