# Generated by Django 2.1.7 on 2019-02-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_auto_20180916_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('start', 'part'), 'verbose_name': 'ripening season', 'verbose_name_plural': 'ripening seasons'},
        ),
    ]
