# Generated by Django 2.0.8 on 2018-09-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery_ct',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
