# Generated by Django 2.2.28 on 2022-04-23 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fruit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="fruit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="fruit.Fruit"
            ),
        ),
        migrations.AddField(
            model_name="fruit",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fruits", to="fruit.Kind", verbose_name="kind"
            ),
        ),
        migrations.AddField(
            model_name="fruit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fruits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="fruit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="fruit.Fruit"
            ),
        ),
    ]
