# Generated by Django 2.0.13 on 2019-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0010_auto_20170913_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='deleted'),
        ),
    ]
