# Generated by Django 2.0.8 on 2018-08-20 18:11

from django.core.files.base import ContentFile
from django.db import migrations


def copy_images(apps, schema_editor):
    OldImage = apps.get_model('gallery', 'Image')
    NewImage = apps.get_model('fruit', 'Image')

    images = OldImage.objects.filter(gallery_ct__model='fruit')
    count = images.count()

    for n, img in enumerate(images, start=1):
        print('copying {}/{}'.format(n, count))
        with open(img.image.path, 'rb') as old_file:
            NewImage.objects.create(
                fruit_id=img.gallery_id,
                image=ContentFile(old_file.read(), name=img.image.name),
                caption=img.caption,
                author=img.author,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0011_auto_20180820_2008'),
        ('gallery', '0004_alter_image_field'),
    ]

    operations = [
        migrations.RunPython(copy_images)
    ]
