# Generated by Django 2.0.8 on 2018-08-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fruit', '0012_auto_20180820_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', utils.fields.AutoDateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=1600, verbose_name='comment')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name="author's IP address")),
                ('is_complaint', models.BooleanField(default=False, verbose_name='complaint')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='rejected')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fruit.Fruit')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-created',),
            },
        ),
    ]
