# Generated by Django 2.0.8 on 2018-08-21 13:04

from django.db import migrations


def copy_comments(apps, schema_editor):
    OldComment = apps.get_model('comments', 'Comment')
    NewComment = apps.get_model('fruit', 'Comment')

    comments = OldComment.objects.filter(content_type__model='fruit')
    count = comments.count()

    for n, com in enumerate(comments, start=1):
        print('copying comment {}/{}'.format(n, count))

        NewComment.objects.create(
            fruit_id=com.object_id,
            text=com.text,
            author=com.author,
            ip=com.ip,
            is_complaint=com.complaint,
            is_rejected=com.rejected,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0013_comment'),
        ('comments', '0003_added_indexes'),
    ]

    operations = [
        migrations.RunPython(copy_comments)
    ]
