# Generated by Django 2.0.8 on 2018-09-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0015_auto_20180916_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbarium',
            name='kind',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbarium_old', to='fruit.Kind', verbose_name='kind'),
        ),
    ]
