# Generated by Django 2.1.7 on 2019-02-22 12:52

from django.db import migrations, models
import fruit.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0017_auto_20180916_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=fruit.models.image.Image._upload_to, verbose_name='image'),
        ),
    ]
